apiVersion: v1
kind: ServiceAccount
metadata:
  name: mitose
  namespace: mitose
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mitose
  namespace: mitose
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["deployment"]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mitose
  namespace: mitose
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mitose
subjects:
- kind: ServiceAccount
  name: mitose
  namespace: mitose
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: mitose
  name: mitose
  namespace: mitose
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: mitose
    spec:
      containers:
      - name: mitose
        image: luizalabs/mitose:0.0.1
        env:
        - name: PORT
          value: "5000"
        volumeMounts:
        - mountPath: /var/credentials
          name: gcp-credentials
          readOnly: true
      serviceAccountName: mitose
      volumes:
      - name: gcp-credentials
        secret:
          defaultMode: 420
          secretName: credentials
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: mitose
  namespace: mitose
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: mitose
  type: ClusterIP
